### ISSUE TITLE
hugeGraph-client初始化client报错

### ISSUE THREAD

**Issue by 0x554simon** [hugegraph/hugegraph-client#115]
Exception in thread "main" java.lang.NoSuchFieldError: EXCLUDE_EMPTY
	at org.glassfish.jersey.client.ClientConfig$State.<init>(ClientConfig.java:150)
	at org.glassfish.jersey.client.ClientConfig.<init>(ClientConfig.java:468)
	at com.baidu.hugegraph.rest.AbstractRestClient$ConfigBuilder.<init>(AbstractRestClient.java:463)
	at com.baidu.hugegraph.rest.AbstractRestClient.<init>(AbstractRestClient.java:123)
	at com.baidu.hugegraph.client.RestClient.<init>(RestClient.java:55)
	at com.baidu.hugegraph.driver.HugeClient.<init>(HugeClient.java:58)
	at com.baidu.hugegraph.driver.HugeClientBuilder.build(HugeClientBuilder.java:67)

**Comment by Linary** [comment]
@0x554simon 这应该是依赖包冲突导致的，你检查下项目中是否还有添加其他jersey相关的依赖。最好在一个干净的项目中使用hugegraph-client
