### ISSUE TITLE
Exception in thread "main" class com.baidu.hugegraph.HugeException: Failed to commit

### ISSUE THREAD

**Issue by xy83918** [hugegraph/hugegraph-client#23]
follow https://hugegraph.github.io/hugegraph-doc/quickstart/hugegraph-client.html

```
  <properties>
    <hugegraph.version>1.6.4</hugegraph.version>
  </properties>


  <dependencies>
    <dependency>
      <groupId>com.baidu.hugegraph</groupId>
      <artifactId>hugegraph-client</artifactId>
      <version>${hugegraph.version}</version>
    </dependency>
  </dependencies>
```

```
Exception in thread "main" class com.baidu.hugegraph.HugeException: Failed to commit
	at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:44)
	at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:63)
	at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:119)
	at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:79)
	at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:74)
	at com.baidu.hugegraph.api.graph.VertexAPI.create(VertexAPI.java:48)
	at com.baidu.hugegraph.driver.GraphManager.addVertex(GraphManager.java:56)
	at com.baidu.hugegraph.driver.GraphManager.addVertex(GraphManager.java:71)
	at com.sx.graph.huge.SingleExample.main(SingleExample.java:110)
Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
```

如果用客户端 1.5.8 报错

```
Exception in thread "main" java.lang.IllegalStateException: The version 0.31.0.0 of 'hugegraph-api in server' is not in [0.27, 0.28)
	at com.google.common.base.Preconditions.checkState(Preconditions.java:199)
	at com.baidu.hugegraph.util.E.checkState(E.java:68)
	at com.baidu.hugegraph.util.VersionUtil.check(VersionUtil.java:52)
	at com.baidu.hugegraph.driver.HugeClient.checkServerApiVersion(HugeClient.java:102)
	at com.baidu.hugegraph.driver.HugeClient.initManagers(HugeClient.java:84)
	at com.baidu.hugegraph.driver.HugeClient.<init>(HugeClient.java:59)
	at com.baidu.hugegraph.driver.HugeClient.<init>(HugeClient.java:48)
	at com.sx.graph.huge.SingleExample.main(SingleExample.java:21)
```

**Comment by Linary** [comment]
你这个是在一个全新的项目里面测试的吗，看起来像有依赖方面的问题

**Comment by xy83918** [comment]
郁闷啊，搞了两天Demo 跑不起来

```curl "http://lab01:8080/graphs/hugegraph/graph/vertices" | gunzip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   317  100   317    0     0  17750      0 --:--:-- --:--:-- --:--:-- 18647
{"vertices":[{"id":"2:lop","label":"software","type":"vertex","properties":{"price":[{"id":"2:lop>price","value":328}],"name":[{"id":"2:lop>name","value":"lop"}],"lang":[{"id":"2:lop>lang","value":"java"}]}},{"id":"1:josh","label":"person","type":"vertex","properties":{"city":[{"id":"1:josh>city","value":"Beijing"}],"name":[{"id":"1:josh>name","value":"josh"}],"age":[{"id":"1:josh>age","value":32}]}},{"id":"1:marko","label":"person","type":"vertex","properties":{"city":[{"id":"1:marko>city","value":"Beijing"}],"name":[{"id":"1:marko>name","value":"marko"}],"age":[{"id":"1:marko>age","value":29}]}},{"id":"1:peter","label":"person","type":"vertex","properties":{"city":[{"id":"1:peter>city","value":"Shanghai"}],"name":[{"id":"1:peter>name","value":"peter"}],"age":[{"id":"1:peter>age","value":35}]}},{"id":"1:vadas","label":"person","type":"vertex","properties":{"city":[{"id":"1:vadas>city","value":"Hongkong"}],"name":[{"id":"1:vadas>name","value":"vadas"}],"age":[{"id":"1:vadas>age","value":27}]}},{"id":"2:ripple","label":"software","type":"vertex","properties":{"price":[{"id":"2:ripple>price","value":199}],"name":[{"id":"2:ripple>name","value":"ripple"}],"lang":[{"id":"2:ripple>lang","value":"java"}]}}]}%```

```
Exception in thread "main" class javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)
	at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:44)
	at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:64)
	at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:119)
	at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:79)
	at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:74)
	at com.baidu.hugegraph.api.gremlin.GremlinAPI.post(GremlinAPI.java:44)
	at com.baidu.hugegraph.driver.GremlinManager.execute(GremlinManager.java:60)
	at com.baidu.hugegraph.api.gremlin.GremlinRequest$Builder.execute(GremlinRequest.java:57)
	at com.baidu.hugegraph.example.SingleExample.main(SingleExample.java:154)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
```

```   
HugeClient hugeClient = new HugeClient("http://lab01:8080","hugegraph");
```

**Comment by xy83918** [comment]
![image](https://user-images.githubusercontent.com/2715268/49077952-a2bb1600-f277-11e8-8462-055640c98f74.png)

![image](https://user-images.githubusercontent.com/2715268/49077956-a9498d80-f277-11e8-8755-398a5bff1464.png)

**Comment by Linary** [comment]
@xy83918 看你的这个截图，构造HugeClient是成功的，但是发送Gremlin请求失败，应该是GremlinServer的配置改漏了。

你检查一下服务端的两个配置：
- gremlin-server.yaml 的 host 和 port
- rest-server.properties 的 gremlinserver.url
它们一般是不需要改的，如果要改就两个一起改。
