### ISSUE TITLE
Run Example java.net.ConnectException: 

### ISSUE THREAD

**Issue by xy83918** [hugegraph/hugegraph-client#24]
```

		HugeClient hugeClient = new HugeClient("http://lab01:8080", "hugegraph");
		GremlinManager gremlin = hugeClient.gremlin();

		String query = "g.V().hasLabel('character').has('name','hercules').out('father').out('father')";

		ResultSet resultSet = gremlin.gremlin(query).execute();
```

```
Exception in thread "main" class javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)
	at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:44)
	at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:63)
	at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:119)
	at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:79)
	at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:74)
	at com.baidu.hugegraph.api.gremlin.GremlinAPI.post(GremlinAPI.java:41)
	at com.baidu.hugegraph.driver.GremlinManager.execute(GremlinManager.java:50)
	at com.baidu.hugegraph.api.gremlin.GremlinRequest$Builder.execute(GremlinRequest.java:55)
	at com.sx.graph.huge.TitanExample.main(TitanExample.java:81)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
```

**Comment by Linary** [comment]
url 中填 ip 试试

**Comment by Linary** [comment]
@xy83918 可否告知您的环境信息，比如：系统，服务端两个配置文件（gremlin-server.yaml，rest-server.properties）的内容，是直接在IDE里面运行的上述代码，还是打包运行的。

**Comment by Linary** [comment]
你检查一下服务端的两个配置：

gremlin-server.yaml 的 host 和 port
rest-server.properties 的 gremlinserver.url
它们一般是不需要改的，如果要改就两个一起改。
